[package]
name = "l1x-forge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
hex = { workspace = true }
log = { workspace = true }